### PR TITLE
Move logic for interpolated array evaluation into property class.

### PR DESCRIPTION
**Pull request by apontzen**
This will allow it to be overriden for properties that do not interpolate linearly.

A unit test needs to be added

### CODE REVIEW

**Comment by Martin-Rey** [comment]
Hi Andrew,

I am not entirely sure where and what to add as a new test for this PR.

The at() function is already tested here:
https://github.com/pynbody/tangos/blob/359a7f7e3bc17f251ffa6f2725570a6ac7b211b7/tests/test_live_calculation.py#L102-L119
ensuring that the default interpolation does what it should. 

I can't find a test file that goes through the methods of the `PropertyCalculation` class, I assume because most of them are abstract. The only properties that are currently extensively tested are histograms and live properties, none of which require a new interpolation scheme.

The only test I can think of is to create some "dummy property" that overrides the interpolation method, proving that the override mechanics works (which it should, otherwise Python is broken) and test the new implementation (but this implementation would not be used anywhere in the code).

Martin

**Comment by apontzen** [comment]
Yes, I mean the dummy property example. It just checks the correct class method is being called. I've pushed this so will merge assuming no objections.

**Comment by Martin-Rey** [comment]
Ok! Sorry for not understanding what you meant. The new functionality works fine for me, you can merge.

**Comment by apontzen** [comment]
No worries!

**Pull request merged**
