### PR TITLE
Travis CI/Conda/Cython/Numpy intercompatibility issues

### PR DESCRIPTION
**Pull request by apontzen**
An attempt to find out what will work...

### CODE REVIEW

**Comment by Martin-Rey** [comment]
Just want to point out that in your previous failing build (eff9f81 now outdated), pynbody was still installed with numpy 1.15.  pip --force does not replace the numpy version, but install an additional new one. Pynbody still compiled against the old 1.15 numpy version.

You should have used pip --ugrade numpy that forces pip to uninstall the previous version before installing the new version to do what you want?

**Comment by apontzen** [comment]
Good spot, thanks. I am so sick of this issue...

**Comment by apontzen** [comment]
Wow, now that really is bizarre! @Martin-Rey you are correct about manually downloading the git repository...

**Comment by Martin-Rey** [comment]
Wouldn't have bet on that one tbh. Still doesn't really tell us what is going on, but at least it seems to be working...

**Comment by Martin-Rey** [comment]
Is there a reason why you deleted pyramid and pyramid_mako from the pip install statement? 

It seems to be the source of the error, fixed previously here I believe (see 3c262a3db6c296df5f67d86ed376137c461148d9).

**Comment by apontzen** [comment]
Unintentional reversion...

**Pull request merged**
