### PR TITLE
Introduce option for default values within halo stat files

### PR DESCRIPTION
**Pull request by apontzen**
@tobibu does this address your difficulty with PR #98?

### CODE REVIEW

**Comment by TobiBu** [comment]
Hi Andrew,

I fear this does not work with the 'column_translation' for 'n_dm'. At least this version does not work with my file setup.

When I tested my version, the 'column_translations' were not applied for the values used by other 'column_translations'. Thus I had issues subtracting 'None' from other column values. E.g. the 'column_translation' for 'n_dark' needs 'n_gas' and 'n_stars' but will not see the default value.

**Comment by apontzen** [comment]
Rather than solve the general problem of resolving such interdependencies (which is very complex), I suggest just recoding the `n_dark` function to be robust to `None`s (i.e. replace references to `n_gas` with something like `n_gas or 0`)

**Comment by TobiBu** [comment]
> Rather than solve the general problem of resolving such interdependencies (which is very complex), I suggest just recoding the `n_dark` function to be robust to `None`s (i.e. replace references to `n_gas` with something like `n_gas or 0`)

Hi Andrew,

for that I would suggest this line then:

`'n_dm': translations.Function(lambda ngas, nstar, npart: npart - int(0 if ngas is None else ngas) - int(0 if nstar is None else nstar), 'n_gas', 'n_star', 'npart')}`

What do you think?

**Comment by apontzen** [comment]
@TobiBu I have also tried implementing #101 in this branch - let me know how you get on. I called the property `childHalo` to match the existing AHF property `hostHalo`

**Comment by apontzen** [comment]
> > Rather than solve the general problem of resolving such interdependencies (which is very complex), I suggest just recoding the `n_dark` function to be robust to `None`s (i.e. replace references to `n_gas` with something like `n_gas or 0`)
> 
> Hi Andrew,
> 
> for that I would suggest this line then:
> 
> `'n_dm': translations.Function(lambda ngas, nstar, npart: npart - int(0 if ngas is None else ngas) - int(0 if nstar is None else nstar), 'n_gas', 'n_star', 'npart')}`
> 
> What do you think?

Simpler than `0 if ngas is None else ngas`, you can just put `ngas or 0` etc

**Comment by TobiBu** [comment]
> @TobiBu I have also tried implementing #101 in this branch - let me know how you get on. I called the property `childHalo` to match the existing AHF property `hostHalo`

Seems to work fine for me. Thanks a lot.

**Comment by TobiBu** [comment]
> > `'n_dm': translations.Function(lambda ngas, nstar, npart: npart - int(0 if ngas is None else ngas) - int(0 if nstar is None else nstar), 'n_gas', 'n_star', 'npart')}`
> 
> Simpler than `0 if ngas is None else ngas`, you can just put `ngas or 0` etc

I did not know that works. Thanks for the hint.

How do we proceed, should I merge the changes into the pull request or do you merge this branch first ?

**Comment by apontzen** [comment]
I've merged this branch, but you might need to rebase your development branch to the new master so that you can use the new features

**Pull request merged**
