### PR TITLE
Match with slightly unequal timestep times

### PR DESCRIPTION
**Pull request by Martin-Rey**
PR addressing issue #93 

1) The fraction defining two timesteps as having the same time has been moved to the config file.

2) The missing factor in the "across" keyword to make the test relative rather than absolute has been added.

Feel free to comment
Martin

### CODE REVIEW

**Comment by apontzen** [comment]
Looks good, but for some reason the tests are failing...

**Comment by Martin-Rey** [comment]
Yes the reason of test failing is the same as for PR #91 and probably issue #92, which are all related to ([pynbody/pynbody#503](https://github.com/pynbody/pynbody/issues/503)). It has to do with compatibility problems between numpy, cython versions when installing pynbody. I gave a go at isolating it in PR #91 but hadn't had the time to follow it up.

**Comment by apontzen** [comment]
Oh dear me... I wonder whether @sophianasr has any comment, since she managed to fix this bizarre numpy thing in her own installation?

**Comment by SophiaNasr** [comment]
@Martin-Rey have you tried to pip upgrade cython, followed by numpy, and finally, pynbody? This fixed a problem I was having earlier.

**Comment by Martin-Rey** [comment]
Thanks @SophiaNasr and @apontzen!

I have done some mix and match of numpy and cython versions and come to the conclusion that it is a pretty inexplicable bug :)

1) This is not a Tangos issue but rather a pynbody build issue. The failing tangos tests only follow the two pynbody failing tests.

2) I can get ride of this issue and make the test pass (last build in this pull request) by upgrading manually to numpy 1.16 with cython 0.27 and 0.29. However, this numpy version is not yet available in conda (max 1.15), which is why conda --update does not solve the problem but pip --upgrade does.

3) We have versions of Tangos and pynbody with cython 0.29 and both numpy 1.10, 1.13 and 1.15 that successfully worked a few month ago (#88) and a few days ago (https://github.com/pynbody/pynbody/pull/504).

The only difference I can think off is that both in the Tangos automated build and in @SophiaNasr use case, pynbody was installed via pip, rather than clone+python setup.py.

**Comment by apontzen** [comment]
The thing that I don’t understand is that downgrading cython doesn’t seem to help either, which contributes to making this truly baffling.

**Comment by apontzen** [comment]
Thanks for your assistance @sophianasr! @Martin-Rey if you merge the master branch into this one, travis should now pass...

**Pull request merged**
