### PR TITLE
Allowing calculation of center for each pynbody family

### PR DESCRIPTION
**Pull request by Martin-Rey**
Hi all, 

The following PR is a quick refactoring of the centering property to allow calculations on stars and gas independently of the traditional DM shrink center. I tried to mimic the naming conventions in other stellar and gaseous properties, and decided against changing the name of existing center for backward compatibility. Any comments welcome!

Martin

### CODE REVIEW

**Comment by Martin-Rey** [comment]
So, the test failing if the YT test, which I think is unrelated to this PR. It fails for Python 3.6+numpy1.13 and 3.7+numpy1.15 (but succeed for 3.8+numpy1.18): 

```
======================================================================
1715ERROR: test suite for <module 'test_yt' from '/home/travis/build/pynbody/tangos/tests/test_yt.py'>
1716----------------------------------------------------------------------
1717Traceback (most recent call last):
1718  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/nose/suite.py", line 209, in run
1719    self.setUp()
1720  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/nose/suite.py", line 292, in setUp
1721    self.setupContext(ancestor)
1722  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/nose/suite.py", line 315, in setupContext
1723    try_run(context, names)
1724  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/nose/util.py", line 471, in try_run
1725    return func()
1726  File "/home/travis/build/pynbody/tangos/tests/test_yt.py", line 14, in setup
1727    output_manager = yt_outputs.YtChangaAHFInputHandler("test_tipsy_yt")
1728  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/tangos-1.1.1-py3.7.egg/tangos/input_handlers/yt.py", line 15, in __init__
1729    import yt as yt_local
1730  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/yt/__init__.py", line 25, in <module>
1731    from yt.funcs import \
1732  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/yt/funcs.py", line 48, in <module>
1733    from yt.units.yt_array import YTArray, YTQuantity
1734  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/yt/units/__init__.py", line 1, in <module>
1735    from yt.units import unit_symbols
1736  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/yt/units/unit_symbols.py", line 14, in <module>
1737    from yt.units.yt_array import YTQuantity as quan
1738  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/yt/units/yt_array.py", line 39, in <module>
1739    from yt.units.unit_object import Unit, UnitParseError
1740  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/yt/units/unit_object.py", line 34, in <module>
1741    from yt.units.unit_registry import \
1742  File "/home/travis/miniconda/envs/3.7_1.15.1/lib/python3.7/site-packages/yt/units/unit_registry.py", line 21, in <module>
1743    from yt.utilities.lib.fnv_hash import fnv_hash
1744  File "yt/utilities/lib/fnv_hash.pyx", line 1, in init yt.utilities.lib.fnv_hash
1745ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

and 

```
======================================================================
1702ERROR: test suite for <module 'test_yt' from '/home/travis/build/pynbody/tangos/tests/test_yt.py'>
1703----------------------------------------------------------------------
1704Traceback (most recent call last):
1705  File "/home/travis/miniconda/envs/3.6_1.13.1/lib/python3.6/site-packages/nose/suite.py", line 209, in run
1706    self.setUp()
1707  File "/home/travis/miniconda/envs/3.6_1.13.1/lib/python3.6/site-packages/nose/suite.py", line 292, in setUp
1708    self.setupContext(ancestor)
1709  File "/home/travis/miniconda/envs/3.6_1.13.1/lib/python3.6/site-packages/nose/suite.py", line 315, in setupContext
1710    try_run(context, names)
1711  File "/home/travis/miniconda/envs/3.6_1.13.1/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
1712    return func()
1713  File "/home/travis/build/pynbody/tangos/tests/test_yt.py", line 14, in setup
1714    output_manager = yt_outputs.YtChangaAHFInputHandler("test_tipsy_yt")
1715  File "/home/travis/miniconda/envs/3.6_1.13.1/lib/python3.6/site-packages/tangos-1.1.1-py3.6.egg/tangos/input_handlers/yt.py", line 15, in __init__
1716    import yt as yt_local
1717  File "/home/travis/miniconda/envs/3.6_1.13.1/lib/python3.6/site-packages/yt/__init__.py", line 44, in <module>
1718    import yt.utilities.physical_constants as physical_constants
1719AttributeError: module 'yt' has no attribute 'utilities'
```

Has YT undergone recent updates that need to be reflected in Tangos @cphyc ?

**Comment by Martin-Rey** [comment]
Ok, so after investigation, this issue is the same as in #132, and relates to the interaction between the newest YT 3.6 and old numpy versions. 

It is solved by @j-davies-ari in #132 by upgrading all tests to use NUMPY 1.18. Should #132 be merged into the master branch with the updated travis test setup @apontzen? Or are we wishing to keep testing against old numpy versions, in which case the YT version might need restrictions too?

Martin

**Comment by apontzen** [comment]
I have now merged #132 - this was just an oversight. I don't think we need to test against ancient numpy versions.

**Comment by Martin-Rey** [comment]
As for #132, updating the Numpy versions fixes the tests for this PR. Unless there are comments on the code, this is ready to be merged I believe.

**Comment by apontzen** [comment]
Thanks!

**Pull request merged**
